PUSH-17482 migrate to FCM
Pushwoosh/pushwoosh-unity pull request #43
Opened 2019-01-28 09:55 UTC by AAEvstefeev

2019-01-29 07:57 UTC, kaizerzer requested changes

2019-01-29 07:57 UTC, kaizerzer commented on PluginSource/Android/pushwoosh-unityplugin/src/main/java/com/pushwoosh/unityplugin/internal/PushwooshUnityFcmHelper.java
> +        FirebaseApp.initializeApp(context, options);
а что если у пользователя настроен фаербейз? ну например он аналитику там юзает или еще что. что тогда тут произойдет? какой конфиг заюзается?

2019-01-29 08:30 UTC, AAEvstefeev commented on PluginSource/Android/pushwoosh-unityplugin/src/main/java/com/pushwoosh/unityplugin/internal/PushwooshUnityFcmHelper.java
> +        FirebaseApp.initializeApp(context, options);
по правде сказать все упадет. Добавил проверку. Если он firbase инициализирован то будет конфиг из аналитики использоваться. Возможно еще стоит сделать как-нибудь в самом юнити что бы google-play.json копировал из корня перед сборкой в assets сам. Тогда не будет неоднозначности.

2019-01-30 06:09 UTC, kaizerzer commented on PluginSource/Android/pushwoosh-unityplugin/src/main/java/com/pushwoosh/unityplugin/internal/PushwooshUnityFcmHelper.java
> +        FirebaseApp.initializeApp(context, options);
Да

2019-01-31 10:14 UTC, kaizerzer approved these changes

2019-01-31 10:16 UTC, merged